

WIDTH, HEIGHT = 450, 450
FULLWIDTH = WIDTH + 150
WINDOW_BACKGROUND = "white"


CELLWIDTH = WIDTH / 9
CELL_BACKGROUND = "cyan4"
TEXTCOLOR = "white"
NUMBERFONT = "Consolas"

LINECOLOR = "black"


BUTTONOFFSET = ( FULLWIDTH - WIDTH ) * 0.05
BUTTONHEIGHT = HEIGHT / 10
BUTTONWIDTH = ( FULLWIDTH - WIDTH ) * 0.9
BUTTONTEXTCOLOR = "black"
BUTTONFONT = "Consolas"
BUTTONFONTSIZE = 12

